on: [push]

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - uses: seanzhengw/sphinx-pages@master
      working-directory: ./help
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_readme: true
